### ISSUE TITLE
tacomall-ma启动报错

### ISSUE THREAD

**Issue by Mr-snail** [codingtalk/tacomall#11]
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
15:36:32.046 ModuleBuildError: Module build failed (from ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/sass-loader/dist/cjs.js):
15:36:32.059 SassError: File to import not found or unreadable: @/uni_modules/uview-ui/theme.scss.
15:36:32.068         on line 1 of ../../../../../../Users/snail/WeChatProjects/tacomall/tacomall-ma/uni.scss
15:36:32.075         from line 51 of /Users/snail/WeChatProjects/tacomall/tacomall-ma/App.vue
15:36:32.083 >> @import '@/uni_modules/uview-ui/theme.scss';
15:36:32.092    ^
15:36:32.100     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/webpack/lib/NormalModule.js:316:20
15:36:32.108     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/loader-runner/lib/LoaderRunner.js:367:11
15:36:32.115     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/loader-runner/lib/LoaderRunner.js:233:18
15:36:32.116     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/loader-runner/lib/LoaderRunner.js:111:13
15:36:32.124     at Object.callback (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/packages/sass-loader/dist/index.js:75:7)
15:36:32.132     at Object.done [as callback] (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/neo-async/async.js:8067:18)
15:36:32.139     at /Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-node-sass/node_modules/node-sass-china/lib/index.js:294:32
15:36:32.146 文件查找失败：'@/uni_modules/uview-ui' at main.js:17
15:36:32.153 文件查找失败：'@/uni_modules/uview-ui/components/u-modal/u-modal.vue' at subpackage/member/pages/account/index.vue:5

**Comment by Mr-snail** [comment]
已经执行过npm install
